---
resources:
  - name: resource-tutorial
    type: git
    source:
      uri: https://github.com/walquis/concourse-tutorial-stark-and-wayne.git
      branch: master
      git_config:
      - name: safe.directory
        value: "*"
  - name: my-timer
    type: time
    source:
      interval: 2m

jobs:
  - name: job-hw
    public: true
    serial: true
    plan:
      - get: resource-tutorial
      - get: my-timer
        trigger: true
      - task: hello-world
        file: resource-tutorial/tutorials/basic/task-hello-world/task_hello_world.yml
